### ISSUE TITLE
no such option: --configuration

### ISSUE THREAD

**Issue by byashimov** [jezdez/django-configurations#120] opened 2015-07-26 06:57 UTC
I'm not sure if you accept django 1.8 issues since #105, but this is happen when I use django-compressor command `compress`

```python
./manage.py compress --configuration=Prod
Usage: ./manage.py compress [options] 
Compress content outside of the request/response cycle
./manage.py: error: no such option: --configuration
```

django (1.8.3)
django-configurations (master)
django-compressor (1.4—1.5)

Everything else seems to work well here.

**Comment by asergeant01** [comment] 2015-08-07 06:44
I too receive this error

**Comment by jezdez** [comment] 2015-08-09 13:12
Closing as duplicate of #105.

**Closed by jezdez** 2015-08-09 13:12 UTC
